language: python
python:
    - "3.6"
env:
    - DJANGO=2.0
install:
    - pip install Django==$DJANGO
    - pip install flake8
    - pip install codecov

script:
    - "flake8 --show-source student_sys" 
after_success:
  - codecov    

