language: python
python:
    - "3.6"
env:
    - DJANGO=2.0
install:
    - pip install Django==$DJANGO
    - pip install pep8
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 student_sys"
